CREATE TABLE IF NOT EXISTS `production_db`.`user`
(
  `u_id`       INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `u_username` VARCHAR(255)  NOT NULL,
  `u_password` VARCHAR(255) NOT NULL,
  `u_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `u_updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `u_username_UNIQUE` (`u_username` ASC)
)
  ENGINE = InnoDB;